import express, { Router } from "express";
import UserEndpoints from "./admin/user";
import SubscriptionPlanEndpoints from "./admin/subscription";
import HomeEndpoints from "./admin/home";
import AuthEndpoint from "./admin/auth";
import authenticateUser, { isAdministrator } from "../../middleware/authenticate";
const AdminApiEndpoints: Router = express.Router();
AdminApiEndpoints.use('/auth', AuthEndpoint);
AdminApiEndpoints.use('/', authenticateUser, isAdministrator, HomeEndpoints);
AdminApiEndpoints.use('/users', authenticateUser, isAdministrator, UserEndpoints);
AdminApiEndpoints.use('/subscriptions/plans', authenticateUser, isAdministrator, SubscriptionPlanEndpoints);
export default AdminApiEndpoints;