import express, { Router } from "express";
import UserEndpoints from "./admin/user";
import SubscriptionPlanEndpoints from "./admin/subscription-plan";
import HomeEndpoints from "./admin/home";
import AuthEndpoint from "./admin/auth";
import AdminProfileEndpoints from "./admin/profile";
import authenticateUser, { isAdministrator } from "../../middleware/authenticate";
import ReportEndpoints from "./admin/report";
import ReviewQuestionEndpoints from "./admin/review-question";
import SubscriptionEndpoints from "./admin/subscription";
import PostEndpoints from "./admin/post";
import PromoCodeEndpoints from "./admin/promo-code";
import ReviewEndpoints from "./admin/review";
import BookingEndpoints from "./admin/booking";
import HomeController from "../../controllers/admin/HomeController";
const AdminApiEndpoints: Router = express.Router();
AdminApiEndpoints.use('/auth', AuthEndpoint);
AdminApiEndpoints.use('/profile', authenticateUser, isAdministrator, AdminProfileEndpoints);
AdminApiEndpoints.get('/business/:id/generate-qr', HomeController.generateReviewQRCode);
AdminApiEndpoints.use('/', authenticateUser, isAdministrator, HomeEndpoints);
AdminApiEndpoints.use('/users', authenticateUser, isAdministrator, UserEndpoints);
AdminApiEndpoints.use('/subscriptions', authenticateUser, isAdministrator, SubscriptionEndpoints);
AdminApiEndpoints.use('/subscriptions/plans', authenticateUser, isAdministrator, SubscriptionPlanEndpoints);
AdminApiEndpoints.use('/reports', authenticateUser, isAdministrator, ReportEndpoints);
AdminApiEndpoints.use('/review-questions', authenticateUser, isAdministrator, ReviewQuestionEndpoints);
AdminApiEndpoints.use('/posts', authenticateUser, isAdministrator, PostEndpoints);
AdminApiEndpoints.use('/reviews', authenticateUser, isAdministrator, ReviewEndpoints);
AdminApiEndpoints.use('/promo-codes', authenticateUser, isAdministrator, PromoCodeEndpoints);
AdminApiEndpoints.use('/bookings', authenticateUser, isAdministrator, BookingEndpoints);
export default AdminApiEndpoints;