import express, { Router } from "express";
import HomeEndpoints from "./home-api";
import AuthEndpoint from "./auth";
import UserEndpoints from "./user";
import PostEndpoints from "./post";
import authenticateUser from "../../middleware/authenticate";
import UserConnectionEndpoints from "./user-connection";
import ReviewEndpoints from "./review";
import EventEndpoints from "./event";
import StoryEndpoints from "./story";
import NotificationEndpoints from "./notification";
import SearchEndpoints from "./search";
import FAQEndpoints from "./faq";
import ContactUsEndpoints from "./contact";
import AdminApiEndpoints from "./admin";
import ShareEndpoints from "./share";
import FileQueueEndpoints from "./filequeues";
import BusinessEndpoints from "./business";
import SubscriptionEndpoints from "./subscription";
import CollaborationEndpoints from "./collaboration";
import BookingEndpoints from "./booking";
import BookingRoutes from "./booking/booking";
import HotelEndpoints from "./hotel";
import AmenityEndpoints from "./booking/amenity";
import RoomEndpoints from "./booking/room";
import PricePresetEndpoints from "./booking/price-preset";
import BanksEndpoints from "./booking/bank";
import { isBusinessUser } from "../../middleware/authenticate";
const ApiEndpoints: Router = express.Router();
ApiEndpoints.use('', HomeEndpoints);
ApiEndpoints.use('', SubscriptionEndpoints);
ApiEndpoints.use('/auth', AuthEndpoint);
ApiEndpoints.use('/contact-us', ContactUsEndpoints);
ApiEndpoints.use('/faqs', FAQEndpoints);
ApiEndpoints.use('/user', authenticateUser, UserConnectionEndpoints);
ApiEndpoints.use('/user', authenticateUser, UserEndpoints);
ApiEndpoints.use('/business', BusinessEndpoints);
ApiEndpoints.use('/posts', authenticateUser, PostEndpoints);
ApiEndpoints.use('/reviews', ReviewEndpoints);
ApiEndpoints.use('/events', authenticateUser, EventEndpoints);
ApiEndpoints.use('/story', authenticateUser, StoryEndpoints);
ApiEndpoints.use('/notifications', authenticateUser, NotificationEndpoints);
ApiEndpoints.use('/search', authenticateUser, SearchEndpoints);
ApiEndpoints.use('/share', ShareEndpoints);
ApiEndpoints.use('/files-queue', FileQueueEndpoints);
ApiEndpoints.use('/collaboration', authenticateUser, CollaborationEndpoints);
ApiEndpoints.use('/bookings', authenticateUser, BookingRoutes);
ApiEndpoints.use('/booking', BookingEndpoints);
ApiEndpoints.use('/hotels', authenticateUser, isBusinessUser, HotelEndpoints);
ApiEndpoints.use('/amenities', authenticateUser, isBusinessUser, AmenityEndpoints);
ApiEndpoints.use('/rooms', authenticateUser, RoomEndpoints);
ApiEndpoints.use('/price-preset', authenticateUser, isBusinessUser, PricePresetEndpoints);
ApiEndpoints.use('/banks', BanksEndpoints);

//Admin Routes
ApiEndpoints.use('/admin', AdminApiEndpoints)

export default ApiEndpoints;