import express, { Router } from "express";
import HomeEndpoints from "./home-api";
import AuthEndpoint from "./auth";
import UserEndpoints from "./user";
import PostEndpoints from "./post";
import authenticateUser from "../../middleware/authenticate";
import UserConnectionEndpoints from "./user-connection";
const ApiEndpoints: Router = express.Router();
ApiEndpoints.use('/auth', AuthEndpoint);
ApiEndpoints.use('/', HomeEndpoints);
ApiEndpoints.use('/', authenticateUser, UserConnectionEndpoints);
ApiEndpoints.use('/user', authenticateUser, UserEndpoints);
ApiEndpoints.use('/posts', authenticateUser, PostEndpoints);
export default ApiEndpoints;