import express, { Router } from "express";
import ContactUsController from "../../controllers/ContactUsController";
import { createContactApiValidator } from "../../validation/rules/api-validation";
import { validateRequest } from "../../middleware/api-request-validator";
import authenticateUser, { isAdministrator } from "../../middleware/authenticate";
import { paramIDValidationRule } from "../../validation/rules/api-validation";
const ContactUsEndpoints: Router = express.Router();
ContactUsEndpoints.get('/', authenticateUser, isAdministrator, ContactUsController.index);
ContactUsEndpoints.post('/', createContactApiValidator, validateRequest, ContactUsController.store);
ContactUsEndpoints.put('/:id', authenticateUser, isAdministrator, [paramIDValidationRule], validateRequest, ContactUsController.update);
ContactUsEndpoints.delete('/:id', authenticateUser, isAdministrator, [paramIDValidationRule], validateRequest, ContactUsController.destroy);
export default ContactUsEndpoints;