import express, { Router } from "express";
import EventController from "../../controllers/EventController";
import { createEventApiValidator, joinEventApiValidator } from "../../validation/rules/api-validation";
import { validateRequest } from "../../middleware/api-request-validator";
import { diskUpload, s3Upload } from "../../middleware/file-uploading";
import { AwsS3AccessEndpoints } from "../../config/constants";
const EventEndpoints: Router = express.Router();
EventEndpoints.post('/', diskUpload.fields([{ name: 'images', maxCount: 1, }]), createEventApiValidator, validateRequest, EventController.store);
EventEndpoints.put('/:id', diskUpload.fields([{ name: 'images', maxCount: 1, }]), EventController.update);
EventEndpoints.post('/join', joinEventApiValidator, validateRequest, EventController.joinEvent);
export default EventEndpoints;