import express, { Router } from "express";
import ReviewController from "../../controllers/ReviewController";
import { publicReviewApiValidator } from "../../validation/rules/api-validation";
import { validateRequest } from "../../middleware/api-request-validator";
import authenticateUser from "../../middleware/authenticate";
import { diskUpload } from "../../middleware/file-uploading";
const ReviewEndpoints: Router = express.Router();
ReviewEndpoints.post('/', authenticateUser, diskUpload.fields([{ name: 'images', maxCount: 10, }, { name: 'videos', maxCount: 10, }]), ReviewController.store);
ReviewEndpoints.post('/public', diskUpload.fields([{ name: 'images', maxCount: 10, }, { name: 'videos', maxCount: 10, }]), publicReviewApiValidator, validateRequest, ReviewController.publicReview);
export default ReviewEndpoints;