import express, { Router } from "express";
import { createPromoCodeApiValidator, paramIDValidationRule } from "../../../validation/rules/api-validation";
import { validateRequest } from "../../../middleware/api-request-validator";
import PromoCodeController from "../../../controllers/admin/PromoCodeController";
const PromoCodeEndpoints: Router = express.Router();
PromoCodeEndpoints.get('/', PromoCodeController.index);
PromoCodeEndpoints.post('/', createPromoCodeApiValidator, validateRequest, PromoCodeController.store);
PromoCodeEndpoints.put('/:id', PromoCodeController.update);
PromoCodeEndpoints.delete('/:id', [paramIDValidationRule], validateRequest, PromoCodeController.destroy);
export default PromoCodeEndpoints;